networks:
  taski-network:
    driver: bridge

services:
  backend:
    build: ./backend
    image: kandler3/taski-lab-backend
    ports:
      - "8000:8000"
    networks:
      - taski-network
    hostname: backend
  
  frontend:
    build: ./frontend
    image: kandler3/taski-lab-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - taski-network
    
    depends_on:
      - backend
